"""initial clean schema

Revision ID: 176353f7cd50
Revises: 
Create Date: 2026-02-17 09:34:01.695901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '176353f7cd50'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('tier', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('overage_per_request', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('semantic_call_cost', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('request_limit', sa.Integer(), nullable=False),
    sa.Column('hard_limit', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_plan_price_active', 'pricing_plans', ['monthly_price', 'is_active'], unique=False)
    op.create_index('idx_plan_tier_active', 'pricing_plans', ['tier', 'is_active'], unique=False)
    op.create_index(op.f('ix_pricing_plans_id'), 'pricing_plans', ['id'], unique=False)
    op.create_index(op.f('ix_pricing_plans_is_active'), 'pricing_plans', ['is_active'], unique=False)
    op.create_index(op.f('ix_pricing_plans_name'), 'pricing_plans', ['name'], unique=True)
    op.create_index(op.f('ix_pricing_plans_tier'), 'pricing_plans', ['tier'], unique=False)
    op.create_table('trust_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('base_score', sa.Float(), nullable=False),
    sa.Column('hallucination_weight', sa.Float(), nullable=False),
    sa.Column('grounding_weight', sa.Float(), nullable=False),
    sa.Column('high_risk_penalty', sa.Float(), nullable=False),
    sa.Column('medium_risk_penalty', sa.Float(), nullable=False),
    sa.Column('critical_risk_penalty', sa.Float(), nullable=False),
    sa.Column('number_conflict_penalty', sa.Float(), nullable=False),
    sa.Column('confidence_mismatch_penalty', sa.Float(), nullable=False),
    sa.Column('semantic_risk_penalty', sa.Float(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'environment', name='uq_trust_configs_tenant_environment')
    )
    op.create_index('idx_trust_configs_tenant_active', 'trust_configs', ['tenant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_trust_configs_id'), 'trust_configs', ['id'], unique=False)
    op.create_table('usage_meters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('semantic_calls', sa.Integer(), nullable=False),
    sa.Column('total_latency_ms', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('final_billed_cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('is_finalized', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'month', name='uq_tenant_month_usage')
    )
    op.create_index('idx_tenant_month', 'usage_meters', ['tenant_id', 'month'], unique=False)
    op.create_index(op.f('ix_usage_meters_created_at'), 'usage_meters', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_meters_id'), 'usage_meters', ['id'], unique=False)
    op.create_index(op.f('ix_usage_meters_month'), 'usage_meters', ['month'], unique=False)
    op.create_index(op.f('ix_usage_meters_tenant_id'), 'usage_meters', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('owner_email', sa.String(length=150), nullable=True),
    sa.Column('pricing_plan_id', sa.Integer(), nullable=False),
    sa.Column('current_month_usage', sa.Integer(), nullable=False),
    sa.Column('lifetime_usage', sa.Integer(), nullable=False),
    sa.Column('current_month_overage', sa.Integer(), nullable=False),
    sa.Column('current_month_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('billing_cycle_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('billing_cycle_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('is_trial', sa.Boolean(), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_request_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pricing_plan_id'], ['pricing_plans.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tenants_plan_active', 'tenants', ['pricing_plan_id', 'is_active'], unique=False)
    op.create_index('idx_tenants_tenant_active', 'tenants', ['tenant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_is_active'), 'tenants', ['is_active'], unique=False)
    op.create_index(op.f('ix_tenants_tenant_id'), 'tenants', ['tenant_id'], unique=True)
    op.create_table('tenant_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('api_key_hash', sa.String(length=128), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_key_status', 'tenant_api_keys', ['tenant_id', 'is_active'], unique=False)
    op.create_index('idx_tenant_env', 'tenant_api_keys', ['tenant_id', 'environment'], unique=False)
    op.create_index(op.f('ix_tenant_api_keys_api_key_hash'), 'tenant_api_keys', ['api_key_hash'], unique=True)
    op.create_index(op.f('ix_tenant_api_keys_environment'), 'tenant_api_keys', ['environment'], unique=False)
    op.create_index(op.f('ix_tenant_api_keys_id'), 'tenant_api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_api_keys_is_active'), 'tenant_api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_tenant_api_keys_key_prefix'), 'tenant_api_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_tenant_api_keys_tenant_id'), 'tenant_api_keys', ['tenant_id'], unique=False)
    op.create_table('evaluation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('app_name', sa.String(length=100), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('request_type', sa.String(length=50), nullable=True),
    sa.Column('model_provider', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('hallucination_probability', sa.Float(), nullable=False),
    sa.Column('grounding_score', sa.Float(), nullable=False),
    sa.Column('business_risk', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('triggered_keywords', sa.JSON(), nullable=True),
    sa.Column('number_conflict', sa.Boolean(), nullable=True),
    sa.Column('conflict_severity', sa.String(length=20), nullable=True),
    sa.Column('conflict_type', sa.String(length=50), nullable=True),
    sa.Column('confidence_mismatch', sa.Boolean(), nullable=True),
    sa.Column('semantic_risk', sa.Boolean(), nullable=True),
    sa.Column('semantic_similarity', sa.Float(), nullable=True),
    sa.Column('semantic_model', sa.String(length=100), nullable=True),
    sa.Column('recommendation', sa.String(length=20), nullable=False),
    sa.Column('base_request_cost', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('semantic_call_cost', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('total_request_cost', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('plan_name_snapshot', sa.String(length=50), nullable=True),
    sa.Column('plan_request_limit_snapshot', sa.Integer(), nullable=True),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('explanations', sa.JSON(), nullable=True),
    sa.Column('user_query', sa.Text(), nullable=False),
    sa.Column('retrieved_context', sa.JSON(), nullable=True),
    sa.Column('llm_response', sa.Text(), nullable=False),
    sa.Column('atlas_version', sa.String(length=20), nullable=True),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('evaluation_latency_ms', sa.Integer(), nullable=True),
    sa.Column('config_version', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['tenant_api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_hash', 'tenant_id', name='uq_request_hash_tenant')
    )
    op.create_index('idx_app_created', 'evaluation_logs', ['app_name', 'created_at'], unique=False)
    op.create_index('idx_risk_recommendation', 'evaluation_logs', ['business_risk', 'recommendation'], unique=False)
    op.create_index('idx_tenant_active_logs', 'evaluation_logs', ['tenant_id', 'is_deleted'], unique=False)
    op.create_index('idx_tenant_app_date', 'evaluation_logs', ['tenant_id', 'app_name', 'created_at'], unique=False)
    op.create_index('idx_tenant_created', 'evaluation_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_index('idx_trust_score_date', 'evaluation_logs', ['trust_score', 'created_at'], unique=False)
    op.create_index(op.f('ix_evaluation_logs_app_name'), 'evaluation_logs', ['app_name'], unique=False)
    op.create_index(op.f('ix_evaluation_logs_business_risk'), 'evaluation_logs', ['business_risk'], unique=False)
    op.create_index(op.f('ix_evaluation_logs_created_at'), 'evaluation_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_evaluation_logs_environment'), 'evaluation_logs', ['environment'], unique=False)
    op.create_index(op.f('ix_evaluation_logs_id'), 'evaluation_logs', ['id'], unique=False)
    op.create_index(op.f('ix_evaluation_logs_is_deleted'), 'evaluation_logs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_evaluation_logs_recommendation'), 'evaluation_logs', ['recommendation'], unique=False)
    op.create_index(op.f('ix_evaluation_logs_tenant_id'), 'evaluation_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_evaluation_logs_trust_score'), 'evaluation_logs', ['trust_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluation_logs_trust_score'), table_name='evaluation_logs')
    op.drop_index(op.f('ix_evaluation_logs_tenant_id'), table_name='evaluation_logs')
    op.drop_index(op.f('ix_evaluation_logs_recommendation'), table_name='evaluation_logs')
    op.drop_index(op.f('ix_evaluation_logs_is_deleted'), table_name='evaluation_logs')
    op.drop_index(op.f('ix_evaluation_logs_id'), table_name='evaluation_logs')
    op.drop_index(op.f('ix_evaluation_logs_environment'), table_name='evaluation_logs')
    op.drop_index(op.f('ix_evaluation_logs_created_at'), table_name='evaluation_logs')
    op.drop_index(op.f('ix_evaluation_logs_business_risk'), table_name='evaluation_logs')
    op.drop_index(op.f('ix_evaluation_logs_app_name'), table_name='evaluation_logs')
    op.drop_index('idx_trust_score_date', table_name='evaluation_logs')
    op.drop_index('idx_tenant_created', table_name='evaluation_logs')
    op.drop_index('idx_tenant_app_date', table_name='evaluation_logs')
    op.drop_index('idx_tenant_active_logs', table_name='evaluation_logs')
    op.drop_index('idx_risk_recommendation', table_name='evaluation_logs')
    op.drop_index('idx_app_created', table_name='evaluation_logs')
    op.drop_table('evaluation_logs')
    op.drop_index(op.f('ix_tenant_api_keys_tenant_id'), table_name='tenant_api_keys')
    op.drop_index(op.f('ix_tenant_api_keys_key_prefix'), table_name='tenant_api_keys')
    op.drop_index(op.f('ix_tenant_api_keys_is_active'), table_name='tenant_api_keys')
    op.drop_index(op.f('ix_tenant_api_keys_id'), table_name='tenant_api_keys')
    op.drop_index(op.f('ix_tenant_api_keys_environment'), table_name='tenant_api_keys')
    op.drop_index(op.f('ix_tenant_api_keys_api_key_hash'), table_name='tenant_api_keys')
    op.drop_index('idx_tenant_env', table_name='tenant_api_keys')
    op.drop_index('idx_key_status', table_name='tenant_api_keys')
    op.drop_table('tenant_api_keys')
    op.drop_index(op.f('ix_tenants_tenant_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_is_active'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_index('idx_tenants_tenant_active', table_name='tenants')
    op.drop_index('idx_tenants_plan_active', table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_usage_meters_tenant_id'), table_name='usage_meters')
    op.drop_index(op.f('ix_usage_meters_month'), table_name='usage_meters')
    op.drop_index(op.f('ix_usage_meters_id'), table_name='usage_meters')
    op.drop_index(op.f('ix_usage_meters_created_at'), table_name='usage_meters')
    op.drop_index('idx_tenant_month', table_name='usage_meters')
    op.drop_table('usage_meters')
    op.drop_index(op.f('ix_trust_configs_id'), table_name='trust_configs')
    op.drop_index('idx_trust_configs_tenant_active', table_name='trust_configs')
    op.drop_table('trust_configs')
    op.drop_index(op.f('ix_pricing_plans_tier'), table_name='pricing_plans')
    op.drop_index(op.f('ix_pricing_plans_name'), table_name='pricing_plans')
    op.drop_index(op.f('ix_pricing_plans_is_active'), table_name='pricing_plans')
    op.drop_index(op.f('ix_pricing_plans_id'), table_name='pricing_plans')
    op.drop_index('idx_plan_tier_active', table_name='pricing_plans')
    op.drop_index('idx_plan_price_active', table_name='pricing_plans')
    op.drop_table('pricing_plans')
    # ### end Alembic commands ###
